"""empty message

Revision ID: 083ef8437f9c
Revises: 
Create Date: 2023-03-30 13:59:44.668364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083ef8437f9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('tasks', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
